### ISSUE TITLE
Commit ff477be now crashes plots for older chains

### ISSUE THREAD

**Issue by SBouchard01** [cmbant/getdist#129]
Hello ! 
Just reporting a crash I had that might be relevant : Trying to plot chains for older versions (e.g. 1.6) raises the following `AttributeError: 'ParamInfo' object has no attribute 'periodic'`
Not sure if this is intentional, but otherwise, having some retro-compatibility would be nice (if it is possible) to avoid re-creating older MCSamples objects :)

**Comment by SBouchard01** [comment]
Yes, I just saved a simple MCSample object to load it later. A simple example is [this file](https://github.com/DESIHIGH/desihigh/blob/minimal/data/desi_mock_chain.npy) that is used as an example in a notebook on the same repo :
```python
import numpy as np
from getdist import plots
data = np.load('desi_mock_chain.npy', allow_pickle=True).item()
g = plots.get_single_plotter()
g.plot_1d(data, 'Omega_m')
```
This works fine with 1.7.1 but crashes with 1.7.2

**Comment by SBouchard01** [comment]
Here is the trace for `plot_2d` (which also comes from the same attribute call) :
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[6], line 5
      3 data = np.load('desi_mock_chain.npy', allow_pickle=True).item() # This is a getdist.mcsamples.MCSamples object
      4 g = plots.get_single_plotter()
----> 5 g.plot_2d(data, 'Omega_m', 'H0_rd')

File ~\AppData\Roaming\Python\Python312\site-packages\getdist\plots.py:1867, in GetDistPlotter.plot_2d(self, roots, param1, param2, param_pair, shaded, add_legend_proxy, line_offset, proxy_root_exclude, ax, mask_function, **kwargs)
   1865 contour_args = self._make_contour_args(len(roots), **kwargs)
   1866 for i, root in enumerate(roots):
-> 1867     res = self.add_2d_contours(
   1868         root,
   1869         param_pair[0],
   1870         param_pair[1],
   1871         line_offset + i,
   1872         of=len(roots),
   1873         ax=ax,
   1874         mask_function=mask_function,
   1875         add_legend_proxy=add_legend_proxy and root not in proxy_root_exclude,
   1876         **contour_args[i],
   1877     )
   1878     xbounds, ybounds = self._update_limits(res, xbounds, ybounds)
   1879 if xbounds is not None and "lims" not in kwargs:

File ~\AppData\Roaming\Python\Python312\site-packages\getdist\plots.py:1126, in GetDistPlotter.add_2d_contours(self, root, param1, param2, plotno, of, cols, contour_levels, add_legend_proxy, param_pair, density, alpha, ax, mask_function, **kwargs)
   1124     density = root.marginalizedMixture(params=[param1, param2]).density2D()
   1125 else:
-> 1126     density = self.sample_analyser.get_density_grid(
   1127         root, param1, param2, conts=self.settings.num_plot_contours, likes=self.settings.shade_meanlikes
   1128     )
   1129 if density is None:
   1130     if add_legend_proxy:

File ~\AppData\Roaming\Python\Python312\site-packages\getdist\plots.py:641, in MCSampleAnalysis.get_density_grid(self, root, param1, param2, conts, likes)
    639 if not density:
    640     samples = self.samples_for_root(root)
--> 641     density = samples.get2DDensityGridData(param1.name, param2.name, num_plot_contours=conts, meanlikes=likes)
    642     if density is None:
    643         return None

File ~\AppData\Roaming\Python\Python312\site-packages\getdist\mcsamples.py:1891, in MCSamples.get2DDensityGridData(self, j, j2, num_plot_contours, get_density, meanlikes, mask_function, **kwargs)
   1888 convolvesize = xsize + 2 * winw + Win.shape[0]  # larger than needed for selecting fft pixel count
   1890 # Determine convolution mode based on parameter periodicity
-> 1891 if parx.periodic and pary.periodic:
   1892     convolution_mode = "periodic_both"
   1893 elif parx.periodic:

AttributeError: 'ParamInfo' object has no attribute 'periodic'
```
